### ISSUE TITLE
Task list and discussion: data tables - areas and lines

### ISSUE THREAD

**Issue by JDWoodcock** [npct/pct-shiny#242]
- [ ] Remove all the four increases in cycling option. We know baseline and scenario so we dont need to see increases too

- [ ] Add deaths for each scenario
- [ ] Add health economic value for each scenario
- [ ] add walking for each scenario
- [ ] add change in driving for each scenario
- [ ] allow download as csv
- [ ] move columns a bit closer together
- [ ] introducing this extra 16 columns will mean we need to make it more of smart table to let user choose what to see and how to order columns

For more info on how these 'task lists' work, see [here](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments).

**Comment by Robinlovelace** [comment]
I've created a separate issue for 'allow download as csv': https://github.com/npct/pct-shiny/issues/243 heads up @JDWoodcock

**Comment by nikolai-b** [comment]
I think this is superseded by #276 so I'm closing this issue to move what is included in the download all to one issue.  Please re-open if this should remain a separate issue.
